#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np
import soundfile as sf
from PIL import Image, ImageDraw, ImageFont

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from shared.whistle_torch import (
    SpectrogramConfig,
    ensure_mono_float32,
    make_spectrogram_image,
    resample_audio_if_needed,
)


DEFAULT_GROUP_SIZE = 5
DEFAULT_SPECTROGRAMS_PER_FILE = 4
DEFAULT_OUTPUT_DIR = 'test/inference_review_spectrograms'


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            'Create review spectrogram sheets from inference prediction CSVs '
            '(heavy / medium / low detection files).'
        )
    )
    parser.add_argument(
        '--summary-csv',
        default='test/inference_2022_run3_summary/detections_per_file.csv',
        help='Per-file inference summary CSV generated by summarize_inference_outputs.py',
    )
    parser.add_argument(
        '--output-dir',
        default=DEFAULT_OUTPUT_DIR,
        help='Directory where review PNGs and manifests will be written.',
    )
    parser.add_argument(
        '--group-size',
        type=int,
        default=DEFAULT_GROUP_SIZE,
        help='Number of files per category (heavy, medium, low).',
    )
    parser.add_argument(
        '--spectrograms-per-file',
        type=int,
        default=DEFAULT_SPECTROGRAMS_PER_FILE,
        help='Number of sampled detections to render per file.',
    )
    parser.add_argument(
        '--target-fs',
        type=int,
        default=96_000,
        help='Target sample rate used during training spectrogram generation.',
    )
    parser.add_argument(
        '--image-size',
        type=int,
        default=224,
        help='Output spectrogram size in pixels (square).',
    )
    return parser.parse_args()


def load_rows(summary_csv: Path) -> list[dict[str, str]]:
    with summary_csv.open(newline='') as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
    if not rows:
        raise ValueError(f'No rows found in summary CSV: {summary_csv}')
    return rows


def sort_rows_by_detections(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    return sorted(rows, key=lambda row: int(row['detections']), reverse=True)


def select_rows(rows: list[dict[str, str]], group_size: int) -> dict[str, list[dict[str, str]]]:
    sorted_rows = sort_rows_by_detections(rows)
    heavy = sorted_rows[:group_size]
    low = list(reversed(sorted_rows[-group_size:]))

    if len(sorted_rows) <= group_size:
        medium = sorted_rows[:]
    else:
        center = len(sorted_rows) // 2
        half = group_size // 2
        start = max(0, center - half)
        stop = min(len(sorted_rows), start + group_size)
        start = max(0, stop - group_size)
        medium = sorted_rows[start:stop]

    return {
        'heavy': heavy,
        'medium': medium,
        'low': low,
    }


def sample_detection_rows(prediction_csv: Path, n_samples: int) -> list[dict[str, str]]:
    with prediction_csv.open(newline='') as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
    if not rows:
        return []
    if len(rows) <= n_samples:
        return rows
    indices = np.linspace(0, len(rows) - 1, num=n_samples, dtype=int)
    return [rows[index] for index in indices]


def read_audio_window(audio_path: Path, start_sec: float, end_sec: float) -> tuple[int, np.ndarray]:
    with sf.SoundFile(str(audio_path), 'r') as handle:
        fs = int(handle.samplerate)
        start_frame = max(0, int(round(start_sec * fs)))
        stop_frame = max(start_frame + 1, int(round(end_sec * fs)))
        handle.seek(start_frame)
        audio = handle.read(stop_frame - start_frame, dtype='float32', always_2d=False)
    return fs, ensure_mono_float32(audio)


def render_detection_spectrogram(
    audio_path: Path,
    start_sec: float,
    end_sec: float,
    config: SpectrogramConfig,
) -> Image.Image:
    fs, audio = read_audio_window(audio_path, start_sec, end_sec)
    fs, audio = resample_audio_if_needed(audio, fs, config.target_fs)
    image_uint8 = make_spectrogram_image(audio, fs, config)
    return Image.fromarray(image_uint8)


def get_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    try:
        return ImageFont.truetype('DejaVuSans.ttf', size=size)
    except Exception:
        return ImageFont.load_default()


def draw_text(draw: ImageDraw.ImageDraw, xy: tuple[int, int], text: str, font, fill='black') -> None:
    draw.text(xy, text, font=font, fill=fill)


def create_contact_sheet(
    group_name: str,
    rows: list[dict[str, str]],
    output_dir: Path,
    spectrograms_per_file: int,
    config: SpectrogramConfig,
) -> tuple[Path, list[dict[str, object]]]:
    cell_image_size = config.image_size[0]
    margin = 18
    header_height = 72
    file_label_height = 56
    sample_label_height = 22
    row_height = file_label_height + cell_image_size + sample_label_height
    width = margin * (spectrograms_per_file + 1) + cell_image_size * spectrograms_per_file
    height = header_height + len(rows) * (row_height + margin) + margin

    canvas = Image.new('RGB', (width, height), color='white')
    draw = ImageDraw.Draw(canvas)
    title_font = get_font(28)
    label_font = get_font(16)
    small_font = get_font(13)

    draw_text(draw, (margin, 18), f'{group_name.capitalize()} files review', title_font)
    draw_text(
        draw,
        (margin, 46),
        f'{len(rows)} files, {spectrograms_per_file} sampled detections per file',
        small_font,
        fill='dimgray',
    )

    manifest_rows: list[dict[str, object]] = []

    for row_index, row in enumerate(rows):
        y_top = header_height + row_index * (row_height + margin)
        file_name = row['file_name']
        detections = int(row['detections'])
        prediction_csv = Path(row['prediction_csv'])
        recording_path = Path(row['recording_path'])
        sampled_rows = sample_detection_rows(prediction_csv, spectrograms_per_file)

        draw_text(
            draw,
            (margin, y_top),
            f'{row_index + 1}. {file_name}  |  detections={detections}  |  per_hour={row["detections_per_hour"]}',
            label_font,
        )

        for sample_index, detection_row in enumerate(sampled_rows):
            start_sec = float(detection_row['initial_point'])
            end_sec = float(detection_row['finish_point'])
            confidence = float(detection_row['confidence'])
            x_left = margin + sample_index * (cell_image_size + margin)
            y_image = y_top + file_label_height

            image = render_detection_spectrogram(
                recording_path,
                start_sec,
                end_sec,
                config=config,
            )
            canvas.paste(image, (x_left, y_image))
            draw_text(
                draw,
                (x_left, y_image + cell_image_size + 4),
                f'{start_sec:.1f}-{end_sec:.1f}s  conf={confidence:.3f}',
                small_font,
                fill='dimgray',
            )

            manifest_rows.append(
                {
                    'group': group_name,
                    'file_name': file_name,
                    'recording_path': str(recording_path),
                    'prediction_csv': str(prediction_csv),
                    'detections': detections,
                    'detections_per_hour': row['detections_per_hour'],
                    'sample_index': sample_index,
                    'start_seconds': start_sec,
                    'end_seconds': end_sec,
                    'confidence': confidence,
                }
            )

    output_path = output_dir / f'{group_name}_review.png'
    canvas.save(output_path)
    return output_path, manifest_rows


def main() -> None:
    args = parse_args()

    summary_csv = Path(args.summary_csv).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = load_rows(summary_csv)
    selected = select_rows(rows, args.group_size)

    config = SpectrogramConfig(
        image_size=(args.image_size, args.image_size),
        target_fs=args.target_fs,
    )

    manifest = {
        'summary_csv': str(summary_csv),
        'output_dir': str(output_dir),
        'group_size': args.group_size,
        'spectrograms_per_file': args.spectrograms_per_file,
        'target_fs': args.target_fs,
        'groups': {},
    }

    all_manifest_rows: list[dict[str, object]] = []
    for group_name, group_rows in selected.items():
        output_path, manifest_rows = create_contact_sheet(
            group_name=group_name,
            rows=group_rows,
            output_dir=output_dir,
            spectrograms_per_file=args.spectrograms_per_file,
            config=config,
        )
        manifest['groups'][group_name] = {
            'image_path': str(output_path),
            'files': [
                {
                    'file_name': row['file_name'],
                    'detections': int(row['detections']),
                    'detections_per_hour': row['detections_per_hour'],
                }
                for row in group_rows
            ],
        }
        all_manifest_rows.extend(manifest_rows)

    manifest_path = output_dir / 'manifest.json'
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + '\n')

    manifest_csv_path = output_dir / 'sample_manifest.csv'
    with manifest_csv_path.open('w', newline='') as handle:
        field_names = [
            'group',
            'file_name',
            'recording_path',
            'prediction_csv',
            'detections',
            'detections_per_hour',
            'sample_index',
            'start_seconds',
            'end_seconds',
            'confidence',
        ]
        writer = csv.DictWriter(handle, fieldnames=field_names)
        writer.writeheader()
        writer.writerows(all_manifest_rows)

    for group_name, payload in manifest['groups'].items():
        print(f'{group_name}: {payload["image_path"]}')
    print(f'manifest: {manifest_path}')
    print(f'sample csv: {manifest_csv_path}')


if __name__ == '__main__':
    main()
